/**
 *
 *  WorkItems.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "WorkItems.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::grad_project;

const std::string WorkItems::Cols::_work_item_id = "\"work_item_id\"";
const std::string WorkItems::Cols::_owner_node_id = "\"owner_node_id\"";
const std::string WorkItems::Cols::_parent_work_item_id = "\"parent_work_item_id\"";
const std::string WorkItems::Cols::_owner_user_id = "\"owner_user_id\"";
const std::string WorkItems::Cols::_title = "\"title\"";
const std::string WorkItems::Cols::_description = "\"description\"";
const std::string WorkItems::Cols::_status = "\"status\"";
const std::string WorkItems::Cols::_priority = "\"priority\"";
const std::string WorkItems::Cols::_weight = "\"weight\"";
const std::string WorkItems::Cols::_progress = "\"progress\"";
const std::string WorkItems::Cols::_start_date = "\"start_date\"";
const std::string WorkItems::Cols::_due_date = "\"due_date\"";
const std::string WorkItems::Cols::_create_at = "\"create_at\"";
const std::string WorkItems::primaryKeyName = "work_item_id";
const bool WorkItems::hasPrimaryKey = true;
const std::string WorkItems::tableName = "\"work_items\"";

const std::vector<typename WorkItems::MetaData> WorkItems::metaData_={
{"work_item_id","std::string","character varying",50,0,1,1},
{"owner_node_id","int32_t","integer",4,0,0,1},
{"parent_work_item_id","std::string","character varying",50,0,0,0},
{"owner_user_id","std::string","character varying",50,0,0,1},
{"title","std::string","character varying",200,0,0,1},
{"description","std::string","text",0,0,0,0},
{"status","std::string","character varying",20,0,0,1},
{"priority","int32_t","integer",4,0,0,1},
{"weight","int32_t","integer",4,0,0,1},
{"progress","int32_t","integer",4,0,0,1},
{"start_date","::trantor::Date","date",0,0,0,0},
{"due_date","::trantor::Date","date",0,0,0,0},
{"create_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &WorkItems::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
WorkItems::WorkItems(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["work_item_id"].isNull())
        {
            workItemId_=std::make_shared<std::string>(r["work_item_id"].as<std::string>());
        }
        if(!r["owner_node_id"].isNull())
        {
            ownerNodeId_=std::make_shared<int32_t>(r["owner_node_id"].as<int32_t>());
        }
        if(!r["parent_work_item_id"].isNull())
        {
            parentWorkItemId_=std::make_shared<std::string>(r["parent_work_item_id"].as<std::string>());
        }
        if(!r["owner_user_id"].isNull())
        {
            ownerUserId_=std::make_shared<std::string>(r["owner_user_id"].as<std::string>());
        }
        if(!r["title"].isNull())
        {
            title_=std::make_shared<std::string>(r["title"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["priority"].isNull())
        {
            priority_=std::make_shared<int32_t>(r["priority"].as<int32_t>());
        }
        if(!r["weight"].isNull())
        {
            weight_=std::make_shared<int32_t>(r["weight"].as<int32_t>());
        }
        if(!r["progress"].isNull())
        {
            progress_=std::make_shared<int32_t>(r["progress"].as<int32_t>());
        }
        if(!r["start_date"].isNull())
        {
            auto daysStr = r["start_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["due_date"].isNull())
        {
            auto daysStr = r["due_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["create_at"].isNull())
        {
            auto timeStr = r["create_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            workItemId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            ownerNodeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            parentWorkItemId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            ownerUserId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            title_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            priority_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            weight_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            progress_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

WorkItems::WorkItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            workItemId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            ownerNodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            parentWorkItemId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            ownerUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            title_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            weight_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            progress_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

WorkItems::WorkItems(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("work_item_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["work_item_id"].isNull())
        {
            workItemId_=std::make_shared<std::string>(pJson["work_item_id"].asString());
        }
    }
    if(pJson.isMember("owner_node_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["owner_node_id"].isNull())
        {
            ownerNodeId_=std::make_shared<int32_t>((int32_t)pJson["owner_node_id"].asInt64());
        }
    }
    if(pJson.isMember("parent_work_item_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["parent_work_item_id"].isNull())
        {
            parentWorkItemId_=std::make_shared<std::string>(pJson["parent_work_item_id"].asString());
        }
    }
    if(pJson.isMember("owner_user_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["owner_user_id"].isNull())
        {
            ownerUserId_=std::make_shared<std::string>(pJson["owner_user_id"].asString());
        }
    }
    if(pJson.isMember("title"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["title"].isNull())
        {
            title_=std::make_shared<std::string>(pJson["title"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("priority"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["priority"].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson["priority"].asInt64());
        }
    }
    if(pJson.isMember("weight"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["weight"].isNull())
        {
            weight_=std::make_shared<int32_t>((int32_t)pJson["weight"].asInt64());
        }
    }
    if(pJson.isMember("progress"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["progress"].isNull())
        {
            progress_=std::make_shared<int32_t>((int32_t)pJson["progress"].asInt64());
        }
    }
    if(pJson.isMember("start_date"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["start_date"].isNull())
        {
            auto daysStr = pJson["start_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("due_date"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["due_date"].isNull())
        {
            auto daysStr = pJson["due_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("create_at"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["create_at"].isNull())
        {
            auto timeStr = pJson["create_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WorkItems::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            workItemId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            ownerNodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            parentWorkItemId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            ownerUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            title_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            weight_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            progress_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[11]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void WorkItems::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("work_item_id"))
    {
        if(!pJson["work_item_id"].isNull())
        {
            workItemId_=std::make_shared<std::string>(pJson["work_item_id"].asString());
        }
    }
    if(pJson.isMember("owner_node_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["owner_node_id"].isNull())
        {
            ownerNodeId_=std::make_shared<int32_t>((int32_t)pJson["owner_node_id"].asInt64());
        }
    }
    if(pJson.isMember("parent_work_item_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["parent_work_item_id"].isNull())
        {
            parentWorkItemId_=std::make_shared<std::string>(pJson["parent_work_item_id"].asString());
        }
    }
    if(pJson.isMember("owner_user_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["owner_user_id"].isNull())
        {
            ownerUserId_=std::make_shared<std::string>(pJson["owner_user_id"].asString());
        }
    }
    if(pJson.isMember("title"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["title"].isNull())
        {
            title_=std::make_shared<std::string>(pJson["title"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("priority"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["priority"].isNull())
        {
            priority_=std::make_shared<int32_t>((int32_t)pJson["priority"].asInt64());
        }
    }
    if(pJson.isMember("weight"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["weight"].isNull())
        {
            weight_=std::make_shared<int32_t>((int32_t)pJson["weight"].asInt64());
        }
    }
    if(pJson.isMember("progress"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["progress"].isNull())
        {
            progress_=std::make_shared<int32_t>((int32_t)pJson["progress"].asInt64());
        }
    }
    if(pJson.isMember("start_date"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["start_date"].isNull())
        {
            auto daysStr = pJson["start_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            startDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("due_date"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["due_date"].isNull())
        {
            auto daysStr = pJson["due_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            dueDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("create_at"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["create_at"].isNull())
        {
            auto timeStr = pJson["create_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &WorkItems::getValueOfWorkItemId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(workItemId_)
        return *workItemId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItems::getWorkItemId() const noexcept
{
    return workItemId_;
}
void WorkItems::setWorkItemId(const std::string &pWorkItemId) noexcept
{
    workItemId_ = std::make_shared<std::string>(pWorkItemId);
    dirtyFlag_[0] = true;
}
void WorkItems::setWorkItemId(std::string &&pWorkItemId) noexcept
{
    workItemId_ = std::make_shared<std::string>(std::move(pWorkItemId));
    dirtyFlag_[0] = true;
}
const typename WorkItems::PrimaryKeyType & WorkItems::getPrimaryKey() const
{
    assert(workItemId_);
    return *workItemId_;
}

const int32_t &WorkItems::getValueOfOwnerNodeId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(ownerNodeId_)
        return *ownerNodeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WorkItems::getOwnerNodeId() const noexcept
{
    return ownerNodeId_;
}
void WorkItems::setOwnerNodeId(const int32_t &pOwnerNodeId) noexcept
{
    ownerNodeId_ = std::make_shared<int32_t>(pOwnerNodeId);
    dirtyFlag_[1] = true;
}

const std::string &WorkItems::getValueOfParentWorkItemId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(parentWorkItemId_)
        return *parentWorkItemId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItems::getParentWorkItemId() const noexcept
{
    return parentWorkItemId_;
}
void WorkItems::setParentWorkItemId(const std::string &pParentWorkItemId) noexcept
{
    parentWorkItemId_ = std::make_shared<std::string>(pParentWorkItemId);
    dirtyFlag_[2] = true;
}
void WorkItems::setParentWorkItemId(std::string &&pParentWorkItemId) noexcept
{
    parentWorkItemId_ = std::make_shared<std::string>(std::move(pParentWorkItemId));
    dirtyFlag_[2] = true;
}
void WorkItems::setParentWorkItemIdToNull() noexcept
{
    parentWorkItemId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &WorkItems::getValueOfOwnerUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ownerUserId_)
        return *ownerUserId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItems::getOwnerUserId() const noexcept
{
    return ownerUserId_;
}
void WorkItems::setOwnerUserId(const std::string &pOwnerUserId) noexcept
{
    ownerUserId_ = std::make_shared<std::string>(pOwnerUserId);
    dirtyFlag_[3] = true;
}
void WorkItems::setOwnerUserId(std::string &&pOwnerUserId) noexcept
{
    ownerUserId_ = std::make_shared<std::string>(std::move(pOwnerUserId));
    dirtyFlag_[3] = true;
}

const std::string &WorkItems::getValueOfTitle() const noexcept
{
    static const std::string defaultValue = std::string();
    if(title_)
        return *title_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItems::getTitle() const noexcept
{
    return title_;
}
void WorkItems::setTitle(const std::string &pTitle) noexcept
{
    title_ = std::make_shared<std::string>(pTitle);
    dirtyFlag_[4] = true;
}
void WorkItems::setTitle(std::string &&pTitle) noexcept
{
    title_ = std::make_shared<std::string>(std::move(pTitle));
    dirtyFlag_[4] = true;
}

const std::string &WorkItems::getValueOfDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItems::getDescription() const noexcept
{
    return description_;
}
void WorkItems::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[5] = true;
}
void WorkItems::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[5] = true;
}
void WorkItems::setDescriptionToNull() noexcept
{
    description_.reset();
    dirtyFlag_[5] = true;
}

const std::string &WorkItems::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &WorkItems::getStatus() const noexcept
{
    return status_;
}
void WorkItems::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[6] = true;
}
void WorkItems::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[6] = true;
}

const int32_t &WorkItems::getValueOfPriority() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(priority_)
        return *priority_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WorkItems::getPriority() const noexcept
{
    return priority_;
}
void WorkItems::setPriority(const int32_t &pPriority) noexcept
{
    priority_ = std::make_shared<int32_t>(pPriority);
    dirtyFlag_[7] = true;
}

const int32_t &WorkItems::getValueOfWeight() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(weight_)
        return *weight_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WorkItems::getWeight() const noexcept
{
    return weight_;
}
void WorkItems::setWeight(const int32_t &pWeight) noexcept
{
    weight_ = std::make_shared<int32_t>(pWeight);
    dirtyFlag_[8] = true;
}

const int32_t &WorkItems::getValueOfProgress() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(progress_)
        return *progress_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &WorkItems::getProgress() const noexcept
{
    return progress_;
}
void WorkItems::setProgress(const int32_t &pProgress) noexcept
{
    progress_ = std::make_shared<int32_t>(pProgress);
    dirtyFlag_[9] = true;
}

const ::trantor::Date &WorkItems::getValueOfStartDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(startDate_)
        return *startDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WorkItems::getStartDate() const noexcept
{
    return startDate_;
}
void WorkItems::setStartDate(const ::trantor::Date &pStartDate) noexcept
{
    startDate_ = std::make_shared<::trantor::Date>(pStartDate.roundDay());
    dirtyFlag_[10] = true;
}
void WorkItems::setStartDateToNull() noexcept
{
    startDate_.reset();
    dirtyFlag_[10] = true;
}

const ::trantor::Date &WorkItems::getValueOfDueDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(dueDate_)
        return *dueDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WorkItems::getDueDate() const noexcept
{
    return dueDate_;
}
void WorkItems::setDueDate(const ::trantor::Date &pDueDate) noexcept
{
    dueDate_ = std::make_shared<::trantor::Date>(pDueDate.roundDay());
    dirtyFlag_[11] = true;
}
void WorkItems::setDueDateToNull() noexcept
{
    dueDate_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &WorkItems::getValueOfCreateAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createAt_)
        return *createAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &WorkItems::getCreateAt() const noexcept
{
    return createAt_;
}
void WorkItems::setCreateAt(const ::trantor::Date &pCreateAt) noexcept
{
    createAt_ = std::make_shared<::trantor::Date>(pCreateAt);
    dirtyFlag_[12] = true;
}
void WorkItems::setCreateAtToNull() noexcept
{
    createAt_.reset();
    dirtyFlag_[12] = true;
}

void WorkItems::updateId(const uint64_t id)
{
}

const std::vector<std::string> &WorkItems::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "work_item_id",
        "owner_node_id",
        "parent_work_item_id",
        "owner_user_id",
        "title",
        "description",
        "status",
        "priority",
        "weight",
        "progress",
        "start_date",
        "due_date",
        "create_at"
    };
    return inCols;
}

void WorkItems::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getWorkItemId())
        {
            binder << getValueOfWorkItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getOwnerNodeId())
        {
            binder << getValueOfOwnerNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getParentWorkItemId())
        {
            binder << getValueOfParentWorkItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOwnerUserId())
        {
            binder << getValueOfOwnerUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTitle())
        {
            binder << getValueOfTitle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPriority())
        {
            binder << getValueOfPriority();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getWeight())
        {
            binder << getValueOfWeight();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getProgress())
        {
            binder << getValueOfProgress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getStartDate())
        {
            binder << getValueOfStartDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getDueDate())
        {
            binder << getValueOfDueDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreateAt())
        {
            binder << getValueOfCreateAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> WorkItems::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void WorkItems::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getWorkItemId())
        {
            binder << getValueOfWorkItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getOwnerNodeId())
        {
            binder << getValueOfOwnerNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getParentWorkItemId())
        {
            binder << getValueOfParentWorkItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getOwnerUserId())
        {
            binder << getValueOfOwnerUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTitle())
        {
            binder << getValueOfTitle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getPriority())
        {
            binder << getValueOfPriority();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getWeight())
        {
            binder << getValueOfWeight();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getProgress())
        {
            binder << getValueOfProgress();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getStartDate())
        {
            binder << getValueOfStartDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getDueDate())
        {
            binder << getValueOfDueDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreateAt())
        {
            binder << getValueOfCreateAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value WorkItems::toJson() const
{
    Json::Value ret;
    if(getWorkItemId())
    {
        ret["work_item_id"]=getValueOfWorkItemId();
    }
    else
    {
        ret["work_item_id"]=Json::Value();
    }
    if(getOwnerNodeId())
    {
        ret["owner_node_id"]=getValueOfOwnerNodeId();
    }
    else
    {
        ret["owner_node_id"]=Json::Value();
    }
    if(getParentWorkItemId())
    {
        ret["parent_work_item_id"]=getValueOfParentWorkItemId();
    }
    else
    {
        ret["parent_work_item_id"]=Json::Value();
    }
    if(getOwnerUserId())
    {
        ret["owner_user_id"]=getValueOfOwnerUserId();
    }
    else
    {
        ret["owner_user_id"]=Json::Value();
    }
    if(getTitle())
    {
        ret["title"]=getValueOfTitle();
    }
    else
    {
        ret["title"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getPriority())
    {
        ret["priority"]=getValueOfPriority();
    }
    else
    {
        ret["priority"]=Json::Value();
    }
    if(getWeight())
    {
        ret["weight"]=getValueOfWeight();
    }
    else
    {
        ret["weight"]=Json::Value();
    }
    if(getProgress())
    {
        ret["progress"]=getValueOfProgress();
    }
    else
    {
        ret["progress"]=Json::Value();
    }
    if(getStartDate())
    {
        ret["start_date"]=getStartDate()->toDbStringLocal();
    }
    else
    {
        ret["start_date"]=Json::Value();
    }
    if(getDueDate())
    {
        ret["due_date"]=getDueDate()->toDbStringLocal();
    }
    else
    {
        ret["due_date"]=Json::Value();
    }
    if(getCreateAt())
    {
        ret["create_at"]=getCreateAt()->toDbStringLocal();
    }
    else
    {
        ret["create_at"]=Json::Value();
    }
    return ret;
}

std::string WorkItems::toString() const
{
    return toJson().toStyledString();
}

Json::Value WorkItems::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getWorkItemId())
            {
                ret[pMasqueradingVector[0]]=getValueOfWorkItemId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getOwnerNodeId())
            {
                ret[pMasqueradingVector[1]]=getValueOfOwnerNodeId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getParentWorkItemId())
            {
                ret[pMasqueradingVector[2]]=getValueOfParentWorkItemId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getOwnerUserId())
            {
                ret[pMasqueradingVector[3]]=getValueOfOwnerUserId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTitle())
            {
                ret[pMasqueradingVector[4]]=getValueOfTitle();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[5]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[6]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getPriority())
            {
                ret[pMasqueradingVector[7]]=getValueOfPriority();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getWeight())
            {
                ret[pMasqueradingVector[8]]=getValueOfWeight();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getProgress())
            {
                ret[pMasqueradingVector[9]]=getValueOfProgress();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getStartDate())
            {
                ret[pMasqueradingVector[10]]=getStartDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getDueDate())
            {
                ret[pMasqueradingVector[11]]=getDueDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getCreateAt())
            {
                ret[pMasqueradingVector[12]]=getCreateAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getWorkItemId())
    {
        ret["work_item_id"]=getValueOfWorkItemId();
    }
    else
    {
        ret["work_item_id"]=Json::Value();
    }
    if(getOwnerNodeId())
    {
        ret["owner_node_id"]=getValueOfOwnerNodeId();
    }
    else
    {
        ret["owner_node_id"]=Json::Value();
    }
    if(getParentWorkItemId())
    {
        ret["parent_work_item_id"]=getValueOfParentWorkItemId();
    }
    else
    {
        ret["parent_work_item_id"]=Json::Value();
    }
    if(getOwnerUserId())
    {
        ret["owner_user_id"]=getValueOfOwnerUserId();
    }
    else
    {
        ret["owner_user_id"]=Json::Value();
    }
    if(getTitle())
    {
        ret["title"]=getValueOfTitle();
    }
    else
    {
        ret["title"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getPriority())
    {
        ret["priority"]=getValueOfPriority();
    }
    else
    {
        ret["priority"]=Json::Value();
    }
    if(getWeight())
    {
        ret["weight"]=getValueOfWeight();
    }
    else
    {
        ret["weight"]=Json::Value();
    }
    if(getProgress())
    {
        ret["progress"]=getValueOfProgress();
    }
    else
    {
        ret["progress"]=Json::Value();
    }
    if(getStartDate())
    {
        ret["start_date"]=getStartDate()->toDbStringLocal();
    }
    else
    {
        ret["start_date"]=Json::Value();
    }
    if(getDueDate())
    {
        ret["due_date"]=getDueDate()->toDbStringLocal();
    }
    else
    {
        ret["due_date"]=Json::Value();
    }
    if(getCreateAt())
    {
        ret["create_at"]=getCreateAt()->toDbStringLocal();
    }
    else
    {
        ret["create_at"]=Json::Value();
    }
    return ret;
}

bool WorkItems::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("work_item_id"))
    {
        if(!validJsonOfField(0, "work_item_id", pJson["work_item_id"], err, true))
            return false;
    }
    else
    {
        err="The work_item_id column cannot be null";
        return false;
    }
    if(pJson.isMember("owner_node_id"))
    {
        if(!validJsonOfField(1, "owner_node_id", pJson["owner_node_id"], err, true))
            return false;
    }
    else
    {
        err="The owner_node_id column cannot be null";
        return false;
    }
    if(pJson.isMember("parent_work_item_id"))
    {
        if(!validJsonOfField(2, "parent_work_item_id", pJson["parent_work_item_id"], err, true))
            return false;
    }
    if(pJson.isMember("owner_user_id"))
    {
        if(!validJsonOfField(3, "owner_user_id", pJson["owner_user_id"], err, true))
            return false;
    }
    else
    {
        err="The owner_user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("title"))
    {
        if(!validJsonOfField(4, "title", pJson["title"], err, true))
            return false;
    }
    else
    {
        err="The title column cannot be null";
        return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(5, "description", pJson["description"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("priority"))
    {
        if(!validJsonOfField(7, "priority", pJson["priority"], err, true))
            return false;
    }
    if(pJson.isMember("weight"))
    {
        if(!validJsonOfField(8, "weight", pJson["weight"], err, true))
            return false;
    }
    if(pJson.isMember("progress"))
    {
        if(!validJsonOfField(9, "progress", pJson["progress"], err, true))
            return false;
    }
    if(pJson.isMember("start_date"))
    {
        if(!validJsonOfField(10, "start_date", pJson["start_date"], err, true))
            return false;
    }
    if(pJson.isMember("due_date"))
    {
        if(!validJsonOfField(11, "due_date", pJson["due_date"], err, true))
            return false;
    }
    if(pJson.isMember("create_at"))
    {
        if(!validJsonOfField(12, "create_at", pJson["create_at"], err, true))
            return false;
    }
    return true;
}
bool WorkItems::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WorkItems::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("work_item_id"))
    {
        if(!validJsonOfField(0, "work_item_id", pJson["work_item_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("owner_node_id"))
    {
        if(!validJsonOfField(1, "owner_node_id", pJson["owner_node_id"], err, false))
            return false;
    }
    if(pJson.isMember("parent_work_item_id"))
    {
        if(!validJsonOfField(2, "parent_work_item_id", pJson["parent_work_item_id"], err, false))
            return false;
    }
    if(pJson.isMember("owner_user_id"))
    {
        if(!validJsonOfField(3, "owner_user_id", pJson["owner_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("title"))
    {
        if(!validJsonOfField(4, "title", pJson["title"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(5, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("priority"))
    {
        if(!validJsonOfField(7, "priority", pJson["priority"], err, false))
            return false;
    }
    if(pJson.isMember("weight"))
    {
        if(!validJsonOfField(8, "weight", pJson["weight"], err, false))
            return false;
    }
    if(pJson.isMember("progress"))
    {
        if(!validJsonOfField(9, "progress", pJson["progress"], err, false))
            return false;
    }
    if(pJson.isMember("start_date"))
    {
        if(!validJsonOfField(10, "start_date", pJson["start_date"], err, false))
            return false;
    }
    if(pJson.isMember("due_date"))
    {
        if(!validJsonOfField(11, "due_date", pJson["due_date"], err, false))
            return false;
    }
    if(pJson.isMember("create_at"))
    {
        if(!validJsonOfField(12, "create_at", pJson["create_at"], err, false))
            return false;
    }
    return true;
}
bool WorkItems::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool WorkItems::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 200)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 200)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
