/**
 *
 *  OrganizationNodes.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "OrganizationNodes.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::grad_project;

const std::string OrganizationNodes::Cols::_node_id = "\"node_id\"";
const std::string OrganizationNodes::Cols::_node_type = "\"node_type\"";
const std::string OrganizationNodes::Cols::_parent_node_id = "\"parent_node_id\"";
const std::string OrganizationNodes::Cols::_name = "\"name\"";
const std::string OrganizationNodes::Cols::_path = "\"path\"";
const std::string OrganizationNodes::Cols::_create_at = "\"create_at\"";
const std::string OrganizationNodes::primaryKeyName = "node_id";
const bool OrganizationNodes::hasPrimaryKey = true;
const std::string OrganizationNodes::tableName = "\"organization_nodes\"";

const std::vector<typename OrganizationNodes::MetaData> OrganizationNodes::metaData_={
{"node_id","int32_t","integer",4,1,1,1},
{"node_type","std::string","character varying",20,0,0,1},
{"parent_node_id","int32_t","integer",4,0,0,0},
{"name","std::string","character varying",100,0,0,1},
{"path","std::string","ARRAY",0,0,0,1},
{"create_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &OrganizationNodes::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
OrganizationNodes::OrganizationNodes(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r["node_id"].as<int32_t>());
        }
        if(!r["node_type"].isNull())
        {
            nodeType_=std::make_shared<std::string>(r["node_type"].as<std::string>());
        }
        if(!r["parent_node_id"].isNull())
        {
            parentNodeId_=std::make_shared<int32_t>(r["parent_node_id"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["path"].isNull())
        {
            path_=std::make_shared<std::string>(r["path"].as<std::string>());
        }
        if(!r["create_at"].isNull())
        {
            auto timeStr = r["create_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            nodeType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            parentNodeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            path_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

OrganizationNodes::OrganizationNodes(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nodeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            parentNodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            path_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

OrganizationNodes::OrganizationNodes(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("node_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("node_type"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["node_type"].isNull())
        {
            nodeType_=std::make_shared<std::string>(pJson["node_type"].asString());
        }
    }
    if(pJson.isMember("parent_node_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["parent_node_id"].isNull())
        {
            parentNodeId_=std::make_shared<int32_t>((int32_t)pJson["parent_node_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("path"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["path"].isNull())
        {
            path_=std::make_shared<std::string>(pJson["path"].asString());
        }
    }
    if(pJson.isMember("create_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["create_at"].isNull())
        {
            auto timeStr = pJson["create_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void OrganizationNodes::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            nodeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            parentNodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            path_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void OrganizationNodes::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("node_id"))
    {
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("node_type"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["node_type"].isNull())
        {
            nodeType_=std::make_shared<std::string>(pJson["node_type"].asString());
        }
    }
    if(pJson.isMember("parent_node_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["parent_node_id"].isNull())
        {
            parentNodeId_=std::make_shared<int32_t>((int32_t)pJson["parent_node_id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("path"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["path"].isNull())
        {
            path_=std::make_shared<std::string>(pJson["path"].asString());
        }
    }
    if(pJson.isMember("create_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["create_at"].isNull())
        {
            auto timeStr = pJson["create_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &OrganizationNodes::getValueOfNodeId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(nodeId_)
        return *nodeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationNodes::getNodeId() const noexcept
{
    return nodeId_;
}
void OrganizationNodes::setNodeId(const int32_t &pNodeId) noexcept
{
    nodeId_ = std::make_shared<int32_t>(pNodeId);
    dirtyFlag_[0] = true;
}
const typename OrganizationNodes::PrimaryKeyType & OrganizationNodes::getPrimaryKey() const
{
    assert(nodeId_);
    return *nodeId_;
}

const std::string &OrganizationNodes::getValueOfNodeType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(nodeType_)
        return *nodeType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrganizationNodes::getNodeType() const noexcept
{
    return nodeType_;
}
void OrganizationNodes::setNodeType(const std::string &pNodeType) noexcept
{
    nodeType_ = std::make_shared<std::string>(pNodeType);
    dirtyFlag_[1] = true;
}
void OrganizationNodes::setNodeType(std::string &&pNodeType) noexcept
{
    nodeType_ = std::make_shared<std::string>(std::move(pNodeType));
    dirtyFlag_[1] = true;
}

const int32_t &OrganizationNodes::getValueOfParentNodeId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(parentNodeId_)
        return *parentNodeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationNodes::getParentNodeId() const noexcept
{
    return parentNodeId_;
}
void OrganizationNodes::setParentNodeId(const int32_t &pParentNodeId) noexcept
{
    parentNodeId_ = std::make_shared<int32_t>(pParentNodeId);
    dirtyFlag_[2] = true;
}
void OrganizationNodes::setParentNodeIdToNull() noexcept
{
    parentNodeId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &OrganizationNodes::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrganizationNodes::getName() const noexcept
{
    return name_;
}
void OrganizationNodes::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[3] = true;
}
void OrganizationNodes::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[3] = true;
}

const std::string &OrganizationNodes::getValueOfPath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(path_)
        return *path_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrganizationNodes::getPath() const noexcept
{
    return path_;
}
void OrganizationNodes::setPath(const std::string &pPath) noexcept
{
    path_ = std::make_shared<std::string>(pPath);
    dirtyFlag_[4] = true;
}
void OrganizationNodes::setPath(std::string &&pPath) noexcept
{
    path_ = std::make_shared<std::string>(std::move(pPath));
    dirtyFlag_[4] = true;
}

const ::trantor::Date &OrganizationNodes::getValueOfCreateAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createAt_)
        return *createAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OrganizationNodes::getCreateAt() const noexcept
{
    return createAt_;
}
void OrganizationNodes::setCreateAt(const ::trantor::Date &pCreateAt) noexcept
{
    createAt_ = std::make_shared<::trantor::Date>(pCreateAt);
    dirtyFlag_[5] = true;
}
void OrganizationNodes::setCreateAtToNull() noexcept
{
    createAt_.reset();
    dirtyFlag_[5] = true;
}

void OrganizationNodes::updateId(const uint64_t id)
{
}

const std::vector<std::string> &OrganizationNodes::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "node_type",
        "parent_node_id",
        "name",
        "path",
        "create_at"
    };
    return inCols;
}

void OrganizationNodes::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNodeType())
        {
            binder << getValueOfNodeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getParentNodeId())
        {
            binder << getValueOfParentNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPath())
        {
            binder << getValueOfPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreateAt())
        {
            binder << getValueOfCreateAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> OrganizationNodes::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void OrganizationNodes::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getNodeType())
        {
            binder << getValueOfNodeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getParentNodeId())
        {
            binder << getValueOfParentNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPath())
        {
            binder << getValueOfPath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreateAt())
        {
            binder << getValueOfCreateAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value OrganizationNodes::toJson() const
{
    Json::Value ret;
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getNodeType())
    {
        ret["node_type"]=getValueOfNodeType();
    }
    else
    {
        ret["node_type"]=Json::Value();
    }
    if(getParentNodeId())
    {
        ret["parent_node_id"]=getValueOfParentNodeId();
    }
    else
    {
        ret["parent_node_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getPath())
    {
        ret["path"]=getValueOfPath();
    }
    else
    {
        ret["path"]=Json::Value();
    }
    if(getCreateAt())
    {
        ret["create_at"]=getCreateAt()->toDbStringLocal();
    }
    else
    {
        ret["create_at"]=Json::Value();
    }
    return ret;
}

std::string OrganizationNodes::toString() const
{
    return toJson().toStyledString();
}

Json::Value OrganizationNodes::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getNodeId())
            {
                ret[pMasqueradingVector[0]]=getValueOfNodeId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getNodeType())
            {
                ret[pMasqueradingVector[1]]=getValueOfNodeType();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getParentNodeId())
            {
                ret[pMasqueradingVector[2]]=getValueOfParentNodeId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[3]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPath())
            {
                ret[pMasqueradingVector[4]]=getValueOfPath();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCreateAt())
            {
                ret[pMasqueradingVector[5]]=getCreateAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getNodeType())
    {
        ret["node_type"]=getValueOfNodeType();
    }
    else
    {
        ret["node_type"]=Json::Value();
    }
    if(getParentNodeId())
    {
        ret["parent_node_id"]=getValueOfParentNodeId();
    }
    else
    {
        ret["parent_node_id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getPath())
    {
        ret["path"]=getValueOfPath();
    }
    else
    {
        ret["path"]=Json::Value();
    }
    if(getCreateAt())
    {
        ret["create_at"]=getCreateAt()->toDbStringLocal();
    }
    else
    {
        ret["create_at"]=Json::Value();
    }
    return ret;
}

bool OrganizationNodes::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(0, "node_id", pJson["node_id"], err, true))
            return false;
    }
    if(pJson.isMember("node_type"))
    {
        if(!validJsonOfField(1, "node_type", pJson["node_type"], err, true))
            return false;
    }
    else
    {
        err="The node_type column cannot be null";
        return false;
    }
    if(pJson.isMember("parent_node_id"))
    {
        if(!validJsonOfField(2, "parent_node_id", pJson["parent_node_id"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("path"))
    {
        if(!validJsonOfField(4, "path", pJson["path"], err, true))
            return false;
    }
    else
    {
        err="The path column cannot be null";
        return false;
    }
    if(pJson.isMember("create_at"))
    {
        if(!validJsonOfField(5, "create_at", pJson["create_at"], err, true))
            return false;
    }
    return true;
}
bool OrganizationNodes::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrganizationNodes::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(0, "node_id", pJson["node_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("node_type"))
    {
        if(!validJsonOfField(1, "node_type", pJson["node_type"], err, false))
            return false;
    }
    if(pJson.isMember("parent_node_id"))
    {
        if(!validJsonOfField(2, "parent_node_id", pJson["parent_node_id"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("path"))
    {
        if(!validJsonOfField(4, "path", pJson["path"], err, false))
            return false;
    }
    if(pJson.isMember("create_at"))
    {
        if(!validJsonOfField(5, "create_at", pJson["create_at"], err, false))
            return false;
    }
    return true;
}
bool OrganizationNodes::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrganizationNodes::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
